name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # enable manual execution

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and test
    strategy:
      matrix:
        os: [ubuntu-latest]
        template: [aoc, servant-server-template, cli-template]
    runs-on: ${{ matrix.os }}

    steps:

      - name: Install act for testing
        uses: actionsflow/setup-act@v1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute hash for cache key
        run: |
          HASH=$(shasum -a 256 ${{ matrix.template }}.hsfiles | awk '{ print $1 }')
          echo "hash=$HASH" >> $GITHUB_ENV

      - name: Cache Stack dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.stack
            ~/.ghcup
          key: stack-${{ runner.os }}-${{ matrix.template }}-${{ env.hash }}

      - name: Generate a new project from template ${{ matrix.template }}
        run: |
          stack new haskell-toy-example ${{ matrix.template }}
          cd haskell-toy-example
          stack test
          act -n -P ubuntu-latest=catthehacker/ubuntu:act-latest
