name: CI 

on:
  push:
    branches: [ main, 'feature/*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # enable manual execution

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true    

jobs:
  build:
    name: Build and test 
    strategy:
      matrix:
        os: [ubuntu-latest]
        template: [simpler-new-template, servant-server-template, cli-template]  
    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Generate a new project from template ${{ matrix.template }}
      run: |
        stack new haskell-toy-example ${{ matrix.template }}
        cd haskell-toy-example
        stack test
