name: CI

on:
  push:
    branches: [ main, 'feature/*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # enable manual execution

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and test
    strategy:
      matrix:
        os: [ubuntu-latest]
        template: [servant-server-template, cli-template]
    runs-on: ${{ matrix.os }}

    steps:

      - name: Install act for testing
        uses: actionsflow/setup-act@v1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate a new project from template ${{ matrix.template }}
        run: |
          stack new haskell-toy-example ${{ matrix.template }}
          cd haskell-toy-example
          stack test
          act -n -P ubuntu-latest=catthehacker/ubuntu:act-latest
